language: python

python:
- '3.6'

sudo: required

cache:
- docker

services:
- docker

install:
- sudo pip install --upgrade pip
- sudo pip install coveralls

script:
- export CURRENT_PATH=`pwd`
- docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter /bin/bash -c "cd $CURRENT_PATH && pip3 install -I -e .[tests] && coverage run -m unittest discover hepdata_converter_ws/testsuite 'test_*'"
- docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter /bin/bash -c "cd $CURRENT_PATH && pip3 install -I -e . && hepdata-converter-ws -v"

after_success:
- coveralls

before_deploy:
- export CURRENT_PATH=`pwd`
- docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter /bin/bash -c "cd $CURRENT_PATH && rm -rf build hepdata_converter_ws.egg-info"

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "c9Zs3cxHmhVBgMa8KWmMVT+XqHN2M1nGd3Oj1+jj/vhduIjRoYmXPxsZAhEb3TKX0qK8iuWUZDIKwHWI+76RzELsvA+M802qWyf7s9PZRI0VWVS4YACgD08fWpgwlAAK+xRQ5euPrKOUTJmS6kAOqvMkWI2YMZtuufO0V9fIYBn7QND8TkuDJhtns1dlFPPpci3AGENKmhNt4AtuBO+r2gzqWUVOwvtv3C8n7LG0JxgsZykNodx2AEzHS7dC2W1Ub+GnZ5bJshB1FushLbUvLD1+c+34qfAtTh4N6HRWUfWelj3kedXr9UFaZyL7ZE5gr1RXFTOlPYBhFEkzr7ZECdsuAEiqczXlOS1r0HgsWOKyVFp8aFlPI8X1yCd5uy1bsax7MVIDWezcUMjlnM8vz59tfQQQ995eR/h8KnyKxpkCDRcaTtUxNAWBBQGiBZf4sNE4MIKE7dhA8dALJ5ytziGvQX8+Kbuw8vSnR1qFH9M7hC8djDFuf+lgSoS/mn2Xp5SDbgLnu404KkS1ogGCs2OIVGcW+GGTslEt1mwkGtXkNm1PyDlnfCN+r7hIAqj0ylJAUoMhp41sv97HufoYetNBGdFwFrUOV8JfORzlRo1/i+38un+wegPTQRsm6cwnfd59/QEhnMH+8twuRgW9iLLqdkIcxS29cl5EF/Ut89M="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: HEPData/hepdata-converter-ws
